"""empty message

Revision ID: 863a394c25f8
Revises: 448c8fb6419c
Create Date: 2017-08-15 14:40:11.761935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863a394c25f8'
down_revision = '448c8fb6419c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('acknowledged', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('from_user', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'from_user')
    op.drop_column('message', 'date')
    op.drop_column('message', 'acknowledged')
    # ### end Alembic commands ###
